apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: demo

spec:
  replicas: 4

  selector:
    matchLabels:
      app: nginx-demo

  template:
    metadata:
      labels:
        app: nginx-demo

    spec:
      nodeSelector:
        workload-role: worker

      containers:
        - name: nginx
          image: nginx:alpine

          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: demo

spec:
  selector:
    app: nginx-demo

  type: NodePort

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
