replicaCount: 1

image:
  repository: docker.io/haziz04/tvms-nvr-demo
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: NodePort
  port: 8080
  nodePort: 30083

nodeSelector:
  workload-role: worker

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 5
